apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-zoiberg-frontend-crzcommon-cert
  namespace: staging-zoiberg-website-frontend
spec:
  secretName: staging-zoiberg-frontend-tls
  dnsNames:
    - staging.zoiberg.crzcommon.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
