apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: zoiberg-website-frontend-hpa
  namespace: zoiberg-website-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zoiberg-website-frontend-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
