name: build-models-and-notebook

on:
  workflow_dispatch:

jobs:
  build-models-and-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run KNN model script
        run: python knn.py

      - name: Run CNN model script
        run: python cnn.py

      - name: Create Jupyter Notebook
        run: python create_notebook.py

      - name: Execute and Convert Notebook
        run: |
          jupyter nbconvert --to notebook --execute ai_model_notebook.ipynb --no-input --output executed_notebook.ipynb
          jupyter nbconvert --to html executed_notebook.ipynb --no-input --output index.html

      - name: Upload Ai model Notebook as artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-results-notebook
          path: ai_model_notebook.ipynb

      - name: Upload Executed Notebook as artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-results-executed-notebook
          path: executed_notebook.ipynb

      - name: Upload HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-results-html
          path: index.html

      - name: 🧱 Ensure target structure on VPS (SSH)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            TARGET_DIR="/var/www/api.ai-pneumonia-detector.dibodev.fr/html"
            sudo mkdir -p "$TARGET_DIR/models/knn"
            sudo mkdir -p "$TARGET_DIR/models/cnn"
            sudo mkdir -p "$TARGET_DIR/scalers/knn"
            sudo chown -R $USER:$USER "$TARGET_DIR"

      - name: 📤 Upload HTML, models, and scalers to VPS (SCP)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          strip_components: 0
          source: |
            index.html
            models/knn/knn_model.joblib
            models/cnn/model.keras
            models/cnn/meta.json
            scalers/knn/scaler.joblib
          target: /var/www/api.ai-pneumonia-detector.dibodev.fr/html