name: deploy_cluster_production

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run KNN model script
        run: python knn_leo.py

      - name: Run CNN model script
        run: python cnn.py

      - name: Create Jupyter Notebook
        run: python create_notebook.py

        - name: Execute and Convert Notebook
        run: |
          jupyter nbconvert --to notebook --execute ai_model_notebook.ipynb --no-input --output executed_notebook.ipynb
          jupyter nbconvert --to html executed_notebook.ipynb --no-input --output index.html
          jupyter nbconvert --to pdf executed_notebook.ipynb --no-input --output index.pdf

      - name: Upload HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-results-html
          path: index.html
          
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-results-pdf
          path: index.pdf

      - name: Upload Notebook as artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-results-notebook
          path: ai_model_notebook.ipynb

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: corentin35/zoiberg-website-frontend:${{ steps.previoustag.outputs.tag }}

      - name: Replace image tag in deployment.yaml for Kubernetes
        run: |
          sed -i 's/\${TAG_VERSION}/'${{ github.sha }}'/g' k8s/production/deployment.yaml

      - name: Connect to the cluster K3S for deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: |
            apply -f k8s/production/namespace.yaml
            -f k8s/production/certificate.yaml
            -f k8s/production/docker-registry-secret.yaml
            -f k8s/production/deployment.yaml
            -f k8s/production/hpa.yaml
            -f k8s/production/ingress.yaml
            -f k8s/production/service.yaml